In [5]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(filepath_or_buffer="ai_student_impact_dataset.csv")
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

### Data Preparation

In [3]:
df.columns = [column.lower() for column in df.columns]
df.head()

,student_id,major_category,year_of_study,pre_semester_gpa,weekly_genai_hours,primary_use_case,prompt_engineering_skill,tool_diversity,paid_subscription,traditional_study_hours,perceived_ai_dependency,institutional_policy,anxiety_level_during_exams,post_semester_gpa,skill_retention_score,burnout_risk_level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  50000 non-null  int64
 1   major_category              50000 non-null  str
 2   year_of_study               50000 non-null  str
 3   pre_semester_gpa            50000 non-null  float64
 4   weekly_genai_hours          50000 non-null  float64
 5   primary_use_case            50000 non-null  str
 6   prompt_engineering_skill    50000 non-null  str
 7   tool_diversity              50000 non-null  int64
 8   paid_subscription           50000 non-null  bool
 9   traditional_study_hours     50000 non-null  float64
 10  perceived_ai_dependency     50000 non-null  int64
 11  institutional_policy        50000 non-null  str
 12  anxiety_level_during_exams  50000 non-null  int64
 13  post_semester_gpa           50000 non-null  float64
 14  skill_retention_score       50000 non-null  float64
 15  burnout_risk_level          50000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(6)
memory usage: 5.8 MB

There is no missing values in our dataset.

#### Detecting Outliers
I will try to find outliers in our dataset by using IQR and Z-score for features such as `weekly_genai_hours`, `pre_semester_gpa` and `post_semester_gpa` by defining one function for each method and then reapplying them whenever needed.

In [10]:
def z_score(df: pd.DataFrame, column_name: str) -> pd.Series:
	mean = df[column_name].mean()
	std = df[column_name].std()

	z_scores = (df[column_name] - mean) / std
	return z_scores

In [12]:
df["weekly_genai_hours_outlier"] = (
    z_score(df=df, column_name="weekly_genai_hours")
)

In [15]:
df[np.abs(df["weekly_genai_hours_outlier"]) > 3]

,student_id,major_category,year_of_study,pre_semester_gpa,weekly_genai_hours,primary_use_case,prompt_engineering_skill,tool_diversity,paid_subscription,traditional_study_hours,perceived_ai_dependency,institutional_policy,anxiety_level_during_exams,post_semester_gpa,skill_retention_score,burnout_risk_level,weekly_genai_hours_outlier
89,100090,Humanities,Graduate,3.544,34.00,Debugging/Troubleshooting,Beginner,2,False,8.67,6,Actively_Encouraged,1,3.795,68.80,High,3.092361
124,100125,STEM,Sophomore,3.446,40.00,Summarizing_Reading,Intermediate,4,False,7.47,10,Actively_Encouraged,2,3.441,76.67,High,3.817920
148,100149,STEM,Sophomore,3.221,40.00,Debugging/Troubleshooting,Beginner,3,True,4.54,6,Allowed_With_Citation,5,3.347,57.02,High,3.817920
149,100150,STEM,Freshman,3.641,35.18,Debugging/Troubleshooting,Advanced,4,True,7.77,8,Actively_Encouraged,6,3.840,51.53,High,3.235054
184,100185,STEM,Freshman,3.022,37.66,Copywriting/Drafting,Intermediate,3,True,7.47,6,Allowed_With_Citation,7,3.260,55.99,Medium,3.534952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49828,149829,Business,Sophomore,3.500,40.00,Direct_Answer_Generation,Intermediate,3,True,3.75,10,Allowed_With_Citation,6,2.910,33.60,High,3.817920
49850,149851,Business,Junior,3.756,33.72,Debugging/Troubleshooting,Intermediate,2,True,11.91,10,Actively_Encouraged,4,4.000,74.90,Medium,3.058502
49877,149878,STEM,Freshman,1.984,35.33,Debugging/Troubleshooting,Advanced,4,False,15.87,9,Allowed_With_Citation,4,2.645,91.06,Medium,3.253193
49908,149909,STEM,Junior,3.624,36.73,Ideation,Intermediate,2,True,4.33,8,Strict_Ban,10,3.826,72.76,High,3.422490
49937,149938,Business,Freshman,3.113,40.00,Direct_Answer_Generation,Intermediate,2,True,14.87,9,Allowed_With_Citation,7,2.875,23.86,High,3.817920