In [4]:
import numpy as np
import pandas as pd

### 1. Environment Setup & Data Loading

In [2]:
df = pd.read_csv(filepath_or_buffer="All_State_NCRB_Crime_Data_2014.csv")
df.head()

,States/UTs,District,Year,Murder,Attempt to commit Murder,Culpable Homicide not amounting to Murder,Attempt to commit Culpable Homicide,Rape,Custodial Rape,Custodial_Gang Rape,...,Offences promoting enmity between different groups,Promoting enmity between different groups,"Imputation, assertions prejudicial to national integration",Extortion,Disclosure of Identity of Victims,Incidence of Rash Driving,HumanTrafficking,Unnatural Offence,Other IPC crimes,Total Cognizable IPC crimes
0,Andhra Pradesh,Anantapur,2014,134,171,8,0,35,0,0,...,0,0,0,0,0,1038,0,0,3800,8376
1,Andhra Pradesh,Chittoor,2014,84,170,2,0,32,0,0,...,0,0,0,19,0,249,0,0,2567,5374
2,Andhra Pradesh,Cuddapah,2014,80,162,1,0,28,0,0,...,0,0,0,0,0,948,0,0,2604,5803
3,Andhra Pradesh,East Godavari,2014,64,84,2,0,85,0,0,...,0,0,0,32,0,39,0,0,3791,7630
4,Andhra Pradesh,Guntakal Railway,2014,14,4,0,0,0,0,0,...,0,0,0,0,0,1,0,0,37,490

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 838 entries, 0 to 837
Data columns (total 91 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   States/UTs                                                        838 non-null    str
 1   District                                                          838 non-null    str
 2   Year                                                              838 non-null    int64
 3   Murder                                                            838 non-null    int64
 4   Attempt to commit Murder                                          838 non-null    int64
 5   Culpable Homicide not amounting to Murder                         838 non-null    int64
 6   Attempt to commit Culpable Homicide                               838 non-null    int64
 7   Rape                                                              838 non-null    int64
 8   Custodial Rape                                                    838 non-null    int64
 9   Custodial_Gang Rape                                               838 non-null    int64
 10  Custodial_Other Rape                                              838 non-null    int64
 11  Rape other than Custodial                                         838 non-null    int64
 12  Rape_Gang Rape                                                    838 non-null    int64
 13  Rape_Others                                                       838 non-null    int64
 14  Attempt to commit Rape                                            838 non-null    int64
 15  Kidnapping & Abduction_Total                                      838 non-null    int64
 16  Kidnapping & Abduction                                            838 non-null    int64
 17  Kidnapping & Abduction in order to Murder                         838 non-null    int64
 18  Kidnapping for Ransom                                             838 non-null    int64
 19  Kidnapping & Abduction of Women to compel her for marriage        838 non-null    int64
 20  Other Kidnapping                                                  838 non-null    int64
 21  Dacoity                                                           838 non-null    int64
 22  Dacoity with Murder                                               838 non-null    int64
 23  Other Dacoity                                                     838 non-null    int64
 24  Making Preparation and Assembly for committing Dacoity            838 non-null    int64
 25  Robbery                                                           838 non-null    int64
 26  Criminal Trespass/Burglary                                        838 non-null    int64
 27  Criminal Trespass or Burglary                                     838 non-null    int64
 28  House Trespass & House Breaking                                   838 non-null    int64
 29  Theft                                                             838 non-null    int64
 30  Auto Theft                                                        838 non-null    int64
 31  Other Thefts                                                      838 non-null    int64
 32  Unlawful Assembly                                                 838 non-null    int64
 33  Riots                                                             838 non-null    int64
 34  Riots_Communal                                                    838 non-null    int64
 35  Riots_Industrial                                                  838 non-null    int64
 36  Riots_Political                                                   838 non-null    int64
 37  Riots_Caste Conflict                                              838 non-null    int64
 38  Riots_SC/STs Vs Non-SCs/STs                                       838 non-null    int64
 39  Riots_Other Caste Conflict                                        838 non-null    int64
 40  Riots_Agrarian                                                    838 non-null    int64
 41  Riots_Students                                                    838 non-null    int64
 42  Riots_Sectarian                                                   838 non-null    int64
 43  Riots_Others                                                      838 non-null    int64
 44  Criminal Breach of Trust                                          838 non-null    int64
 45  Cheating                                                          838 non-null    int64
 46  Forgery                                                           838 non-null    int64
 47  Counterfeiting                                                    838 non-null    int64
 48  Counterfeit Offences related to Counterfeit Coin                  838 non-null    int64
 49  Counterfeiting Government Stamp                                   838 non-null    int64
 50  Counterfeit currency & Bank notes                                 838 non-null    int64
 51  Counterfeiting currency notes/Bank notes                          838 non-null    int64
 52  Using forged or counterfeiting currency/Bank notes                838 non-null    int64
 53  Possession of forged or counterfeiting currency/Bank notes        838 non-null    int64
 54  Making or Possessing materials for forged currency/Bank notes     838 non-null    int64
 55  Making or Using documents resembling currency                     838 non-null    int64
 56  Arson                                                             838 non-null    int64
 57  Grievous Hurt                                                     838 non-null    int64
 58  Hurt                                                              838 non-null    int64
 59  Acid attack                                                       838 non-null    int64
 60  Attempt to Acid Attack                                            838 non-null    int64
 61  Dowry Deaths                                                      838 non-null    int64
 62  Assault on Women with intent to outrage her Modesty               838 non-null    int64
 63  Sexual Harassment                                                 838 non-null    int64
 64  Assault or use of criminal force to women with intent to Disrobe  838 non-null    int64
 65  Voyeurism                                                         838 non-null    int64
 66  Stalking                                                          838 non-null    int64
 67  Other Assault on Women                                            838 non-null    int64
 68  Insult to the Modesty of Women                                    838 non-null    int64
 69  At Office premises                                                838 non-null    int64
 70  Other places related to work                                      838 non-null    int64
 71  In Public Transport system                                        838 non-null    int64
 72  Places other than 231, 232 & 233                                  838 non-null    int64
 73  Cruelty by Husband or his Relatives                               838 non-null    int64
 74  Importation of Girls from Foreign Country                         838 non-null    int64
 75  Causing Death by Negligence                                       838 non-null    int64
 76  Deaths due to negligent driving/act                               838 non-null    int64
 77  Deaths due to Other Causes                                        838 non-null    int64
 78  Offences against State                                            838 non-null    int64
 79  Sedition                                                          838 non-null    int64
 80  Other offences against State                                      838 non-null    int64
 81  Offences promoting enmity between different groups                838 non-null    int64
 82  Promoting enmity between different groups                         838 non-null    int64
 83  Imputation, assertions prejudicial to national integration        838 non-null    int64
 84  Extortion                                                         838 non-null    int64
 85  Disclosure of Identity of Victims                                 838 non-null    int64
 86  Incidence of Rash Driving                                         838 non-null    int64
 87  HumanTrafficking                                                  838 non-null    int64
 88  Unnatural Offence                                                 838 non-null    int64
 89  Other IPC crimes                                                  838 non-null    int64
 90  Total Cognizable IPC crimes                                       838 non-null    int64
dtypes: int64(89), str(2)
memory usage: 595.9 KB

In [7]:
NUMERICAL_COLS = df.select_dtypes(include=np.number).columns
CATEGORICAL_COLS = df.select_dtypes(include="str").columns

### 2. Separation of Aggregates vs. District Granularity

In [11]:
df.head()

,States/UTs,District,Year,Murder,Attempt to commit Murder,Culpable Homicide not amounting to Murder,Attempt to commit Culpable Homicide,Rape,Custodial Rape,Custodial_Gang Rape,...,Offences promoting enmity between different groups,Promoting enmity between different groups,"Imputation, assertions prejudicial to national integration",Extortion,Disclosure of Identity of Victims,Incidence of Rash Driving,HumanTrafficking,Unnatural Offence,Other IPC crimes,Total Cognizable IPC crimes
0,Andhra Pradesh,Anantapur,2014,134,171,8,0,35,0,0,...,0,0,0,0,0,1038,0,0,3800,8376
1,Andhra Pradesh,Chittoor,2014,84,170,2,0,32,0,0,...,0,0,0,19,0,249,0,0,2567,5374
2,Andhra Pradesh,Cuddapah,2014,80,162,1,0,28,0,0,...,0,0,0,0,0,948,0,0,2604,5803
3,Andhra Pradesh,East Godavari,2014,64,84,2,0,85,0,0,...,0,0,0,32,0,39,0,0,3791,7630
4,Andhra Pradesh,Guntakal Railway,2014,14,4,0,0,0,0,0,...,0,0,0,0,0,1,0,0,37,490

In [18]:
df_district = df[df["District"] != "Total"]
df_state_totals = df[df["District"] == "Total"]

if (
    df_district["Total Cognizable IPC crimes"].sum()
    == df_state_totals["Total Cognizable IPC crimes"].sum()
):
    print("No double-counting included")
else:
    print("There is some double-counting")

No double-counting included