In [31]:
import numpy as np
import pandas as pd

from outliers import z_score, calculate_iqr, find_outliers_via_forest

In [32]:
df = pd.read_csv(filepath_or_buffer="Bank Customer Churn Prediction.csv")

In [33]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   credit_score      10000 non-null  int64
 2   country           10000 non-null  str
 3   gender            10000 non-null  str
 4   age               10000 non-null  int64
 5   tenure            10000 non-null  int64
 6   balance           10000 non-null  float64
 7   products_number   10000 non-null  int64
 8   credit_card       10000 non-null  int64
 9   active_member     10000 non-null  int64
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64
dtypes: float64(2), int64(8), str(2)
memory usage: 937.6 KB

In [35]:
df["customer_id"].unique().shape

(10000,)

In [36]:
df = df.drop(columns="customer_id")

### **Detecting Outliers & Anomalies**

In [37]:
numerical_cols = (
    df
    .drop(columns="churn")
    .select_dtypes(include=[np.number])
    .columns
)

anomalies = find_outliers_via_forest(
    df=df, 
    numerical_cols=numerical_cols, 
    contamination=0.05,
    to_scale=False
)

df = pd.concat(objs=[df, anomalies], ignore_index=False, axis="columns")

In [38]:
df.head()

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,anomaly,score
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,0.094068
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,0.070199
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,0.028907
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1,0.056492
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1,0.079036

In [39]:
df.shape

(10000, 13)

In [40]:
df_anomalies = df[df["anomaly"] == -1]
df = df[df["anomaly"] == 1]

In [41]:
df.shape

(9500, 13)